<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pxa_social_feed"
 *
 * Auto generated by Extension Builder 2015-09-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Pixelant Social Media Feed Reader',
	'description' => '',
	'category' => 'plugin',
	'author' => '',
	'author_email' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6-7.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);